/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.cleancode;

import lejos.hardware.motor.EV3LargeRegulatedMotor;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        EV3LargeRegulatedMotor m;
    }
}
